
import os
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from .base_service import BaseService
from .pdf_service import pdf_service
from typing import Dict, Any

# If modifying these SCOPES, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/gmail.send']

class EmailService(BaseService):
    def __init__(self):
        super().__init__("email")
        self.creds = None

    def _get_gmail_service(self):
        """
        Authenticates with Google using credentials.json or existing token.json.
        """
        creds = None
        if os.path.exists(self.settings.GMAIL_TOKEN_PATH):
            creds = Credentials.from_authorized_user_file(self.settings.GMAIL_TOKEN_PATH, SCOPES)
        
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                if not os.path.exists(self.settings.GMAIL_CREDENTIALS_PATH):
                    raise FileNotFoundError(
                        f"Missing {self.settings.GMAIL_CREDENTIALS_PATH}. "
                        "Please download OAuth client secrets from GCP Console."
                    )
                flow = InstalledAppFlow.from_client_secrets_file(
                    self.settings.GMAIL_CREDENTIALS_PATH, SCOPES)
                creds = flow.run_local_server(port=0)
            
            # Save the credentials for the next run
            with open(self.settings.GMAIL_TOKEN_PATH, 'w') as token:
                token.write(creds.to_json())
        
        return build('gmail', 'v1', credentials=creds)

    async def send_analysis_report(self, recipient_email: str, analysis_data: Dict[str, Any], custom_message: str = ""):
        """
        Sends an authenticated Gmail with the Investment Memo attached.
        """
        self.logger.info(f"Initiating Gmail Dispatch to: {recipient_email}")
        
        try:
            service = self._get_gmail_service()
            
            # 1. Generate the PDF
            pdf_bytes = pdf_service.generate_memo_pdf(analysis_data)
            company_name = analysis_data.get('companyName', 'Startup')
            
            # 2. Construct the MIMEMultipart message
            message = MIMEMultipart()
            message['to'] = recipient_email
            message['subject'] = f"Venture Intelligence: {company_name} Investment Memo"
            
            # 3. Body
            body_text = custom_message if custom_message else f"Attached is the institutional-grade investment memo for {company_name}, generated by VentureScout AI."
            message.attach(MIMEText(body_text, 'plain'))
            
            # 4. Attachment
            part = MIMEApplication(pdf_bytes, Name=f"Memo_{company_name}.pdf")
            part['Content-Disposition'] = f'attachment; filename="Memo_{company_name}.pdf"'
            message.attach(part)
            
            # 5. Encode and Send
            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
            send_result = service.users().messages().send(userId="me", body={'raw': raw_message}).execute()
            
            self.logger.info(f"Report successfully sent via Gmail API. ID: {send_result['id']}")
            return {"status": "success", "id": send_result['id']}
            
        except HttpError as error:
            self.log_error("Gmail API Error", error)
            raise Exception(f"Gmail API Failure: {str(error)}")
        except Exception as e:
            self.log_error("Email Dispatch Error", e)
            raise e

email_service = EmailService()
